spring:
  main:
    banner-mode: "off"
  application:
    name: "api-sender-info"
    datasource:
      datasource:
        url: ${DB_URL:jdbc:h2:mem:db;DB_CLOSE_DELAY=-1}
        username: ${DB_USER:sa}
        password: ${DB_PASSWORD:sa}
        continue-on-error: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.web: DEBUG
    com.statflo: DEBUG
    org.hibernate: DEBUG

  spring:
    messages:
      basename: messages
      cache-seconds: -1
      encoding: UTF-8







#